### ISSUE TITLE
Not an issue - Volume instead of OpenInterest

### ISSUE THREAD

**Issue by macieman** [asad70/Options-Max-Pain-Calculator#1]
Hi Asad,
Thanks for writing this tool, its a great code.
Checking in to see, if we can use the Volume instead of OpenInterest, if so can you please suggest what changes has to be done in the code.

**Comment by asad70** [comment]
Hi,
Options pandas df have the following columns:
`
['contractSymbol', 'lastTradeDate', 'strike', 'lastPrice', 'bid', 'ask', 'change', 'percentChange', 'volume', 'openInterest', 'impliedVolatility', 'inTheMoney', 'contractSize', 'currency', 'expirationDate', 'dte', 'CALL']
`

In total_loss_on_strike function changing the following lines 44, 45 and 52, 53 from openInterest to volume would work:
Line 44, 45 from:
` in_money_calls = callChain[callChain['strike'] < expiry_price][["openInterest", "strike"]]`
` in_money_calls["CLoss"] = (expiry_price - in_money_calls['strike'])*in_money_calls["openInterest"]`
To:
` in_money_calls = callChain[callChain['strike'] < expiry_price][["volume", "strike"]]`
` in_money_calls["CLoss"] = (expiry_price - in_money_calls['strike'])*in_money_calls["volume"]`

And line 52, 53 from:
`in_money_puts = putChain[putChain['strike'] > expiry_price][["openInterest", "strike"]]`
` in_money_puts["PLoss"] = (in_money_puts['strike'] - expiry_price)*in_money_puts["openInterest"]`
To
`in_money_puts = putChain[putChain['strike'] > expiry_price][["volume", "strike"]]`
`in_money_puts["PLoss"] = (in_money_puts['strike'] - expiry_price)*in_money_puts["volume"]`

Hope that helps!
